name: Stable Rust Toolchain

on:
  workflow_call:
    inputs:
      targets:
        description: Comma-separated list of target triples to install for this toolchain
        required: false
      components:
        description: Comma-separated list of components to be additionally installed
        required: false

permissions:
  contents: read

runs:
  using: "composite"
  steps:
    # also update in rust-toolchain.toml
    - uses: dtolnay/rust-toolchain@1.89.0
      with:
        targets: ${{ inputs.targets }}
        components: ${{ inputs.components }}
    - run: rm rust-toolchain.toml
      shell: sh
