name: Build Docker test images

on:
  push:
    branches:
      - master
    paths:
      - 'docker/**'
  workflow_dispatch:

concurrency:
  group: docker-builds

env:
  REGISTRY: ghcr.io
  NAMESPACE: fish-ci

jobs:
  docker-build:
    if: github.repository_owner == 'fish-shell'
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: alpine
          - os: ubuntu-latest
            target: ubuntu-oldest-supported
    runs-on: ${{ matrix.os }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.NAMESPACE }}/${{ matrix.target }}
          flavor: |
            latest=true
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker/context
          push: true
          file: docker/${{ matrix.target }}.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
